Change pkg_name for Windows
As the pkg_title is used in package resource declaration
and pkg_name in requires, these must be same. Otherwise
the dependency resolution will fail with error

    Error: Could not find dependency Package[sensu] for
    File[C:/opt/sensu/conf.d] at
    C:/ProgramData/PuppetLabs/code/modules/sensu/manifests/package.pp:102